import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProviderComp from "@/components/ThemeProvider";
import Navbar from "@/components/Header";
import TransitionWrapper from "@/components/TransitionWrapper";
import SessionProviderComp from "@/components/SessionProviderComp";
import { Toaster } from "@/components/ui/sonner";
import ReduxProvider from "@/components/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <SessionProviderComp>
            <ThemeProviderComp>
              <div className="">
                <Navbar />
                <TransitionWrapper>
                  <div className="mt-5">{children}</div>
                </TransitionWrapper>
              </div>
            </ThemeProviderComp>
            <Toaster />
          </SessionProviderComp>
        </ReduxProvider>
      </body>
    </html>
  );
}
